use utils::app_errors::AppError;

pub fn run_part1() -> Result<(), AppError> {
    Ok(())
}

pub fn run_part2() -> Result<(), AppError> {
    Ok(())
}
